import { Product, PRODUCTS } from "./products";

export interface ShowcaseTab {
  id: "best-seller" | "new-arrival" | "back-in-stock" | "upcoming" | "limited-edition";
  label: string;
  bengaliLabel: string;
  tagline: string;
  bengaliTagline: string;
  badge: string;
}

export const SHOWCASE_TABS: ShowcaseTab[] = [
  {
    id: "best-seller",
    label: "Best Seller",
    bengaliLabel: "সর্বোচ্চ বিক্রিত",
    tagline: "Our most coveted artisanal cushions cherished across sanctuaries",
    bengaliTagline: "সবচেয়ে জনপ্রিয় এবং সমাদৃত খাঁটি ফ্যাব্রিক কালেকশন",
    badge: "🔥 BEST SELLER",
  },
  {
    id: "new-arrival",
    label: "New Arrival",
    bengaliLabel: "নতুন আগমন",
    tagline: "Fresh from the loom: stone-washed flax & printed botanicals",
    bengaliTagline: "তাজা তাঁত থেকে আসা নতুন নকশা ও প্যাস্টেল ফ্লাক্স",
    badge: "NEW ARRIVAL",
  },
  {
    id: "back-in-stock",
    label: "Back in Stock",
    bengaliLabel: "পুনরায় স্টকে",
    tagline: "Handcrafted master needlework restocked in small batches",
    bengaliTagline: "হাতে বোনা ঐতিহ্যবাহী কালেকশন পুনরায় সীমিত সংখ্যায় প্রস্তুত",
    badge: "BACK IN STOCK",
  },
  {
    id: "upcoming",
    label: "Upcoming",
    bengaliLabel: "আসন্ন কালেকশন",
    tagline: "Exclusive preview of upcoming ceiling drapes & heirloom quilts",
    bengaliTagline: "আসন্ন ড্র্যাপারি ও ঐতিহ্যবাহী রেশম কাঁথার প্রিভিউ",
    badge: "UPCOMING",
  },
  {
    id: "limited-edition",
    label: "Limited Edition",
    bengaliLabel: "সীমিত সংস্করণ",
    tagline: "Numbered atelier runs: vintage boro patchwork & Jamdani zari",
    bengaliTagline: "সংরক্ষিত সীমিত সংখ্যাক ভিন্টেজ প্যাচওয়ার্ক ও জামদানি কুশন",
    badge: "LIMITED RUN",
  },
];

export const ENRICHED_SHOWCASE_PRODUCTS: Record<string, Product[]> = {
  "best-seller": [
    {
      ...PRODUCTS[2], // Sienna Heavy Matte Velvet
      id: "kc-bs-01",
      name: "Sienna Heavy Matte Velvet",
      price: 2950,
      primaryImage: "https://images.unsplash.com/photo-1616046229478-9901c5536a45?q=80&w=1000&auto=format&fit=crop",
      badge: "🔥 Best Selling",
    },
    {
      ...PRODUCTS[0], // The Marais Belgian Linen
      id: "kc-bs-02",
      name: "The Marais Pure Belgian Linen",
      price: 2450,
      primaryImage: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=1000&auto=format&fit=crop",
      badge: "🔥 Best Selling",
    },
    {
      ...PRODUCTS[4], // The Rajshahi Raw Silk Bolster
      id: "kc-bs-03",
      name: "The Rajshahi Mulberry Silk Bolster",
      price: 3400,
      primaryImage: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?q=80&w=1000&auto=format&fit=crop",
      badge: "🔥 Best Selling",
    },
    {
      ...PRODUCTS[7], // The Atelier Linen & Velvet Combo Set
      id: "kc-bs-04",
      name: "The Atelier Linen & Velvet Duo",
      price: 4850,
      originalPrice: 5400,
      primaryImage: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?q=80&w=1000&auto=format&fit=crop",
      badge: "🔥 Best Selling Combo",
    },
    {
      ...PRODUCTS[1], // Nakshi Heritage Floral Cushion
      id: "kc-bs-05",
      name: "Nakshi Heritage Floral Cushion",
      price: 3800,
      primaryImage: "https://images.unsplash.com/photo-1579656381226-5fc0f0100c3b?q=80&w=1000&auto=format&fit=crop",
      badge: "🔥 Best Selling",
    },
    {
      ...PRODUCTS[6], // The Boro Artisanal Patchwork
      id: "kc-bs-06",
      name: "The Boro Artisanal Patchwork",
      price: 3600,
      primaryImage: "https://images.unsplash.com/photo-1507652313519-d4e9174996dd?q=80&w=1000&auto=format&fit=crop",
      badge: "🔥 Best Selling",
    },
    {
      ...PRODUCTS[2],
      id: "kc-bs-07",
      name: "Venetian Forest Matte Velvet",
      price: 2850,
      primaryImage: "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?q=80&w=1000&auto=format&fit=crop",
      badge: "🔥 Best Selling",
    },
    {
      ...PRODUCTS[5],
      id: "kc-bs-08",
      name: "Bengal Kantha Handloom Square",
      price: 3250,
      primaryImage: "https://images.unsplash.com/photo-1600121848594-d8644e57abab?q=80&w=1000&auto=format&fit=crop",
      badge: "🔥 Best Selling",
    },
  ],
  "new-arrival": [
    {
      id: "kc-na-01",
      name: "Sage Green Printed Pure Flax Cushion",
      tagline: "Stone-washed Belgian flax with artisanal botanical block print",
      price: 2750,
      originalPrice: 3200,
      category: "linen",
      fabric: "100% Organic European Flax Linen",
      closure: "Concealed Antique Brass YKK Zipper",
      fillOption: "Microfiber Plush or Duck Down Insert",
      sizes: ["18\" × 18\"", "20\" × 20\""],
      colors: [{ name: "Sage Botanical Green", hex: "#7E846B" }],
      primaryImage: "https://images.unsplash.com/photo-1600121848594-d8644e57abab?q=80&w=1000&auto=format&fit=crop",
      secondaryImage: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?q=80&w=1000&auto=format&fit=crop",
      description: "As featured in our SS editorial edit. Woven from certified European organic flax and stone-washed.",
      careInstructions: ["Gentle cold machine wash", "Line dry in shade"],
      dimensions: "18\" × 18\" (45cm × 45cm)",
      inStock: true,
      featured: true,
      badge: "NEW ARRIVAL",
    },
    {
      id: "kc-na-02",
      name: "Cascading Belgian Drape Cushion",
      tagline: "Double-flanged pure organic flax in French Lavender",
      price: 2850,
      category: "linen",
      fabric: "European Long-Staple Flax",
      closure: "Concealed YKK zipper",
      fillOption: "Dense Hypoallergenic Microfiber Pad",
      sizes: ["20\" × 20\""],
      colors: [{ name: "French Lavender Grey", hex: "#9E99A3" }],
      primaryImage: "https://images.unsplash.com/photo-1616046229478-9901c5536a45?q=80&w=1000&auto=format&fit=crop",
      secondaryImage: "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?q=80&w=1000&auto=format&fit=crop",
      description: "Elegantly tailored with a 1.5-inch raw-edge tailored flange.",
      careInstructions: ["Machine wash cold"],
      dimensions: "20\" × 20\"",
      inStock: true,
      featured: true,
      badge: "NEW ARRIVAL",
    },
    {
      id: "kc-na-03",
      name: "Nordic Loom Textured Bouclé",
      tagline: "Sculptural heavy bouclé yarn with organic slub texture",
      price: 3200,
      category: "boucle",
      fabric: "Heavy Textured Wool & Cotton Bouclé",
      closure: "Concealed bottom zipper",
      fillOption: "High-Loft Feather Blend",
      sizes: ["18\" × 18\"", "22\" × 22\""],
      colors: [{ name: "Alabaster Ecru", hex: "#EAE6DF" }],
      primaryImage: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=1000&auto=format&fit=crop",
      secondaryImage: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?q=80&w=1000&auto=format&fit=crop",
      description: "Tactile depth with an architectural, cloud-like texture.",
      careInstructions: ["Spot clean only"],
      dimensions: "18\" × 18\"",
      inStock: true,
      badge: "NEW ARRIVAL",
    },
    {
      id: "kc-na-04",
      name: "Avignon Waffle Belgian Linen",
      tagline: "Deep honeycomb texture pre-washed for airy softness",
      price: 2600,
      category: "linen",
      fabric: "100% Belgian Flax Waffle Weave",
      closure: "Concealed brass zipper",
      fillOption: "Microfiber Plush Insert",
      sizes: ["18\" × 18\""],
      colors: [{ name: "Raw Honey Flax", hex: "#D4B07B" }],
      primaryImage: "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?q=80&w=1000&auto=format&fit=crop",
      secondaryImage: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?q=80&w=1000&auto=format&fit=crop",
      description: "Breathable, airy waffle weave loomed from organic flax.",
      careInstructions: ["Machine wash gentle cycle"],
      dimensions: "18\" × 18\"",
      inStock: true,
      badge: "NEW ARRIVAL",
    },
    {
      id: "kc-na-05",
      name: "Kyoto Minimalist Sashiko Pillow",
      tagline: "Geometric running-stitch needlework on unbleached linen",
      price: 3150,
      category: "embroidered",
      fabric: "Pure Belgian Linen & Cotton Sashiko Thread",
      closure: "Mother-of-pearl buttons",
      fillOption: "Dense Hypoallergenic Microfiber",
      sizes: ["18\" × 18\""],
      colors: [{ name: "Ivory & Indigo", hex: "#2B3A42" }],
      primaryImage: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?q=80&w=1000&auto=format&fit=crop",
      secondaryImage: "https://images.unsplash.com/photo-1579656381226-5fc0f0100c3b?q=80&w=1000&auto=format&fit=crop",
      description: "Ancient Japanese geometric running stitch reinterpreted for contemporary living.",
      careInstructions: ["Dry clean recommended"],
      dimensions: "18\" × 18\"",
      inStock: true,
      badge: "NEW ARRIVAL",
    },
    {
      id: "kc-na-06",
      name: "Tuscan Terracotta Flanged Linen",
      tagline: "Raw-edged wide flange in artisanal sun-baked terracotta",
      price: 2900,
      category: "linen",
      fabric: "Heavy Stone-Washed Flax",
      closure: "Concealed side zipper",
      fillOption: "Duck Down Blend",
      sizes: ["20\" × 20\""],
      colors: [{ name: "Tuscan Terracotta", hex: "#B86B52" }],
      primaryImage: "https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=1000&auto=format&fit=crop",
      secondaryImage: "https://images.unsplash.com/photo-1616046229478-9901c5536a45?q=80&w=1000&auto=format&fit=crop",
      description: "Sun-drenched Mediterranean warmth captured in pure stonewashed flax.",
      careInstructions: ["Machine wash cold"],
      dimensions: "20\" × 20\"",
      inStock: true,
      badge: "NEW ARRIVAL",
    },
    {
      id: "kc-na-07",
      name: "Bespoke Indigo Block-Print Lumbar",
      tagline: "Hand-carved teakwood printing on handloom khadi",
      price: 3450,
      category: "embroidered",
      fabric: "100% Handloom Cotton Khadi",
      closure: "Concealed bottom zip",
      fillOption: "Long Lumbar Microfiber Core",
      sizes: ["14\" × 28\""],
      colors: [{ name: "Deep Indigo", hex: "#1D2A3A" }],
      primaryImage: "https://images.unsplash.com/photo-1507652313519-d4e9174996dd?q=80&w=1000&auto=format&fit=crop",
      secondaryImage: "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?q=80&w=1000&auto=format&fit=crop",
      description: "Generous lumbar proportions crafted with naturally fermented indigo dye.",
      careInstructions: ["Gentle hand wash cold"],
      dimensions: "14\" × 28\" (Lumbar)",
      inStock: true,
      badge: "NEW ARRIVAL",
    },
    {
      id: "kc-na-08",
      name: "Alabaster Tufted Wool & Linen Duo",
      tagline: "Architectural raised tufts on heavyweight organic ecru",
      price: 3800,
      category: "linen",
      fabric: "Pure Flax Linen with New Zealand Wool Tufting",
      closure: "Brass zip closure",
      fillOption: "Plush Feather & Down Core",
      sizes: ["18\" × 18\""],
      colors: [{ name: "Alabaster Ecru", hex: "#F5F2EB" }],
      primaryImage: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?q=80&w=1000&auto=format&fit=crop",
      secondaryImage: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=1000&auto=format&fit=crop",
      description: "Sculptural raised wool loops creating an ultra-tactile surface.",
      careInstructions: ["Professional dry clean"],
      dimensions: "18\" × 18\"",
      inStock: true,
      badge: "NEW ARRIVAL",
    },
  ],
  "back-in-stock": [
    {
      id: "kc-bis-01",
      name: "Nakshi Heritage Needlework Cushion",
      tagline: "Intricate hand-embroidered artisanal threadwork",
      price: 3800,
      category: "embroidered",
      fabric: "Handspun Khadi Cotton with Silk Embroidery Threads",
      closure: "Mother-of-pearl button closure",
      fillOption: "Hypoallergenic Microfiber Cushion Pad",
      sizes: ["18\" × 18\"", "20\" × 20\""],
      colors: [{ name: "Champagne Ivory", hex: "#F3EDE2" }],
      primaryImage: "https://images.unsplash.com/photo-1579656381226-5fc0f0100c3b?q=80&w=1000&auto=format&fit=crop",
      secondaryImage: "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?q=80&w=1000&auto=format&fit=crop",
      description: "Restocked after 3 months. Over 40 hours of patient artisan hand-embroidery.",
      careInstructions: ["Strictly dry clean only"],
      dimensions: "18\" × 18\"",
      inStock: true,
      badge: "RESTOCKED",
    },
    {
      id: "kc-bis-02",
      name: "Hitomezashi Sashiko Cushion",
      tagline: "Dense geometric one-stitch grid hand-sewn in pure white",
      price: 3100,
      category: "embroidered",
      fabric: "Pure Flax Linen & Japanese Cotton Thread",
      closure: "Concealed side zipper",
      fillOption: "Microfiber Pad Included",
      sizes: ["18\" × 18\""],
      colors: [{ name: "Obsidian Slate", hex: "#26292B" }],
      primaryImage: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?q=80&w=1000&auto=format&fit=crop",
      secondaryImage: "https://images.unsplash.com/photo-1616046229478-9901c5536a45?q=80&w=1000&auto=format&fit=crop",
      description: "Our fastest selling geometric collection, now available in limited quantities.",
      careInstructions: ["Delicate cycle or dry clean"],
      dimensions: "18\" × 18\"",
      inStock: true,
      badge: "RESTOCKED",
    },
    {
      id: "kc-bis-03",
      name: "Jaipur Block-Printed Botanical Cushion",
      tagline: "Hand-carved teakwood block print with mineral vegetable dyes",
      price: 3100,
      category: "embroidered",
      fabric: "100% Handloom Cotton Cambric",
      closure: "Mother-of-pearl buttons",
      fillOption: "Microfiber Pad Included",
      sizes: ["18\" × 18\""],
      colors: [{ name: "Indigo & Ochre", hex: "#2B3A42" }],
      primaryImage: "https://images.unsplash.com/photo-1507652313519-d4e9174996dd?q=80&w=1000&auto=format&fit=crop",
      secondaryImage: "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?q=80&w=1000&auto=format&fit=crop",
      description: "A beloved heritage favorite restored after being sold out for 4 months.",
      careInstructions: ["Dry clean or hand wash cold"],
      dimensions: "18\" × 18\"",
      inStock: true,
      badge: "RESTOCKED",
    },
    {
      id: "kc-bis-04",
      name: "Avignon Heavy Honeycomb Flax",
      tagline: "320 GSM waffle weave with organic textured depth",
      price: 2600,
      category: "linen",
      fabric: "100% Belgian Flax",
      closure: "Concealed zipper",
      fillOption: "Feather & Down Core",
      sizes: ["20\" × 20\""],
      colors: [{ name: "Raw Ecru", hex: "#E3DAC9" }],
      primaryImage: "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?q=80&w=1000&auto=format&fit=crop",
      secondaryImage: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?q=80&w=1000&auto=format&fit=crop",
      description: "High-density weave loomed from organic long-staple flax.",
      careInstructions: ["Machine wash cold"],
      dimensions: "20\" × 20\"",
      inStock: true,
      badge: "RESTOCKED",
    },
    {
      id: "kc-bis-05",
      name: "Raw Belgian Flax Lumbar Bolster",
      tagline: "Cylindrical bolster loomed with organic French flax",
      price: 2700,
      category: "linen",
      fabric: "Heavy Raw Flax Linen",
      closure: "Double tie-ends",
      fillOption: "Form-Holding Foam & Down Core",
      sizes: ["7\" × 24\""],
      colors: [{ name: "Natural Flax", hex: "#CEC5B4" }],
      primaryImage: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=1000&auto=format&fit=crop",
      secondaryImage: "https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=1000&auto=format&fit=crop",
      description: "Architectural bolster designed for daybeds and reading chaises.",
      careInstructions: ["Spot clean or gentle wash"],
      dimensions: "7\" × 24\" Bolster",
      inStock: true,
      badge: "RESTOCKED",
    },
    {
      id: "kc-bis-06",
      name: "Artisanal Kantha Stitch Cushion",
      tagline: "Hand-carded organic cotton with centuries-old running stitch",
      price: 3300,
      category: "embroidered",
      fabric: "Organic Handspun Cotton",
      closure: "Concealed zipper",
      fillOption: "Microfiber Core",
      sizes: ["18\" × 18\""],
      colors: [{ name: "Oatmeal & Terracotta", hex: "#B86B52" }],
      primaryImage: "https://images.unsplash.com/photo-1600121848594-d8644e57abab?q=80&w=1000&auto=format&fit=crop",
      secondaryImage: "https://images.unsplash.com/photo-1579656381226-5fc0f0100c3b?q=80&w=1000&auto=format&fit=crop",
      description: "Generous hand-quilting imparting tactile warmth and heritage charm.",
      careInstructions: ["Cold hand wash or dry clean"],
      dimensions: "18\" × 18\"",
      inStock: true,
      badge: "RESTOCKED",
    },
    {
      id: "kc-bis-07",
      name: "Sonargaon Gold Zari Muslin Pillow",
      tagline: "Authentic metallic threadwork woven onto sheer cotton muslin",
      price: 4200,
      category: "embroidered",
      fabric: "Fine Cotton Muslin & Gold Zari",
      closure: "Concealed gold zipper",
      fillOption: "Plush Feather Core",
      sizes: ["18\" × 18\""],
      colors: [{ name: "Champagne & Gold", hex: "#D4AF37" }],
      primaryImage: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?q=80&w=1000&auto=format&fit=crop",
      secondaryImage: "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?q=80&w=1000&auto=format&fit=crop",
      description: "Handcrafted tribute to Bengal's historic muslin weaving ateliers.",
      careInstructions: ["Specialist dry clean only"],
      dimensions: "18\" × 18\"",
      inStock: true,
      badge: "RESTOCKED",
    },
    {
      id: "kc-bis-08",
      name: "Stone-Washed Olive Linen Square",
      tagline: "Earthy botanical dye on certified Belgian organic flax",
      price: 2550,
      category: "linen",
      fabric: "100% Belgian Flax",
      closure: "Antique brass zipper",
      fillOption: "Microfiber Pad Included",
      sizes: ["20\" × 20\""],
      colors: [{ name: "Olive Moss", hex: "#556B2F" }],
      primaryImage: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?q=80&w=1000&auto=format&fit=crop",
      secondaryImage: "https://images.unsplash.com/photo-1616046229478-9901c5536a45?q=80&w=1000&auto=format&fit=crop",
      description: "Relaxed European aesthetic with deep, grounding biophilic green tones.",
      careInstructions: ["Machine wash gentle"],
      dimensions: "20\" × 20\"",
      inStock: true,
      badge: "RESTOCKED",
    },
  ],
  "upcoming": [
    {
      id: "kc-up-01",
      name: "Cascading Flax Linen Curtain Panels",
      tagline: "Bespoke ceiling-to-floor drape collection with brass rings",
      price: 5200,
      category: "curtains",
      fabric: "Pure Heavy European Flax Linen 320 GSM",
      closure: "Hand-pleated with brass grommets",
      fillOption: "Unlined semi-sheer drape",
      sizes: ["50\" × 96\"", "50\" × 108\""],
      colors: [{ name: "Raw Ecru Flax", hex: "#D9D0C1" }],
      primaryImage: "https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=1200&auto=format&fit=crop",
      secondaryImage: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?q=80&w=1000&auto=format&fit=crop",
      description: "Coming Autumn 2026. Made to measure floor-skimming drapes.",
      careInstructions: ["Professional dry cleaning"],
      dimensions: "Custom lengths available",
      inStock: false,
      badge: "PREVIEW",
    },
    {
      id: "kc-up-02",
      name: "Heirloom Kantha Silk Bed Quilt",
      tagline: "Hand-stitched vintage Mulberry silk with organic cotton core",
      price: 8500,
      category: "quilts",
      fabric: "100% Pure Rajshahi Mulberry Silk & Khadi Cotton",
      closure: "Bound silk selvedge",
      fillOption: "Fluffy pure cotton batt",
      sizes: ["Queen (90\" × 100\")", "King (108\" × 100\")"],
      colors: [{ name: "Vintage Rose & Pearl", hex: "#C48A80" }],
      primaryImage: "https://images.unsplash.com/photo-1600121848594-d8644e57abab?q=80&w=1000&auto=format&fit=crop",
      secondaryImage: "https://images.unsplash.com/photo-1579656381226-5fc0f0100c3b?q=80&w=1000&auto=format&fit=crop",
      description: "Over 90 hours of hand needlework. Generational craft story.",
      careInstructions: ["Specialist dry clean only"],
      dimensions: "Queen / King",
      inStock: false,
      badge: "PREVIEW",
    },
    {
      id: "kc-up-03",
      name: "The Royal Jamdani Loom Cushion",
      tagline: "Fine muslin weave with genuine gold and silver zari motifs",
      price: 4600,
      category: "embroidered",
      fabric: "Fine Handloom Muslin with Metallic Zari",
      closure: "Concealed gold zipper",
      fillOption: "Duck Down Fill Included",
      sizes: ["18\" × 18\""],
      colors: [{ name: "Midnight Black & Gold", hex: "#1A1A1A" }],
      primaryImage: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?q=80&w=1000&auto=format&fit=crop",
      secondaryImage: "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?q=80&w=1000&auto=format&fit=crop",
      description: "An homage to Dhaka's ancient muslin weaving craft.",
      careInstructions: ["Delicate dry clean only"],
      dimensions: "18\" × 18\"",
      inStock: false,
      badge: "PREVIEW",
    },
    {
      id: "kc-up-04",
      name: "Venetian Double-Pile Velvet Drapes",
      tagline: "Como loomed heavy acoustic blackout velvet panels",
      price: 6800,
      category: "curtains",
      fabric: "100% Italian Cotton-Backed Velvet",
      closure: "French pinch pleat heading",
      fillOption: "Thermal & acoustic lining",
      sizes: ["52\" × 108\""],
      colors: [{ name: "Deep Cypress", hex: "#1E3024" }],
      primaryImage: "https://images.unsplash.com/photo-1616046229478-9901c5536a45?q=80&w=1000&auto=format&fit=crop",
      secondaryImage: "https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=1000&auto=format&fit=crop",
      description: "Unrivalled drape and acoustic serenity for master suites.",
      careInstructions: ["Professional dry cleaning"],
      dimensions: "Custom lengths available",
      inStock: false,
      badge: "PREVIEW",
    },
    {
      id: "kc-up-05",
      name: "Bengal Nakshi Reversible Silk Throw",
      tagline: "Double-sided hand-embroidered Rajshahi silk blanket",
      price: 7200,
      category: "quilts",
      fabric: "Pure Mulberry Silk & Cotton Core",
      closure: "Hand-rolled selvedge",
      fillOption: "Ultra-thin cotton core",
      sizes: ["55\" × 75\""],
      colors: [{ name: "Oatmeal & Copper", hex: "#C27A58" }],
      primaryImage: "https://images.unsplash.com/photo-1579656381226-5fc0f0100c3b?q=80&w=1000&auto=format&fit=crop",
      secondaryImage: "https://images.unsplash.com/photo-1600121848594-d8644e57abab?q=80&w=1000&auto=format&fit=crop",
      description: "Two distinct artisanal color palettes on either side.",
      careInstructions: ["Specialist dry clean"],
      dimensions: "55\" × 75\" Throw",
      inStock: false,
      badge: "PREVIEW",
    },
    {
      id: "kc-up-06",
      name: "Artisanal Hand-Knotted Jute Floor Pillow",
      tagline: "Oversized floor cushion woven from natural Golden Bengal jute",
      price: 3950,
      category: "patchwork",
      fabric: "Natural Jute Fiber & Organic Linen",
      closure: "Heavy brass zipper",
      fillOption: "Dense Firm Support Core",
      sizes: ["26\" × 26\" × 6\""],
      colors: [{ name: "Golden Jute", hex: "#C7A76C" }],
      primaryImage: "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?q=80&w=1000&auto=format&fit=crop",
      secondaryImage: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=1000&auto=format&fit=crop",
      description: "Organic grounding comfort for fireside lounges and terrace sunrooms.",
      careInstructions: ["Brush clean or spot dry"],
      dimensions: "26\" × 26\" Floor Cushion",
      inStock: false,
      badge: "PREVIEW",
    },
    {
      id: "kc-up-07",
      name: "Pure Belgian Flax Sheer Curtains",
      tagline: "Airy translucent daylight filtering drapery panels",
      price: 4900,
      category: "curtains",
      fabric: "160 GSM Sheer Belgian Linen",
      closure: "Dual rod pocket & back tab",
      fillOption: "Airy unlined sheer",
      sizes: ["50\" × 96\""],
      colors: [{ name: "Cloud White", hex: "#FAF9F6" }],
      primaryImage: "https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=1000&auto=format&fit=crop",
      secondaryImage: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?q=80&w=1000&auto=format&fit=crop",
      description: "Diffuses harsh sunshine into ambient, glowing daylight.",
      careInstructions: ["Gentle hand wash cold"],
      dimensions: "50\" × 96\"",
      inStock: false,
      badge: "PREVIEW",
    },
    {
      id: "kc-up-08",
      name: "Atelier Limited Edition Wool Quilt",
      tagline: "Layered organic wool batt with stone-washed flax shell",
      price: 9500,
      category: "quilts",
      fabric: "Pure European Flax & New Zealand Wool Batt",
      closure: "Hand-tied yarn tufts",
      fillOption: "Ultra-Warm Pure Wool Batt",
      sizes: ["King (108\" × 100\")"],
      colors: [{ name: "Raw Ecru", hex: "#E8E4DC" }],
      primaryImage: "https://images.unsplash.com/photo-1600121848594-d8644e57abab?q=80&w=1000&auto=format&fit=crop",
      secondaryImage: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?q=80&w=1000&auto=format&fit=crop",
      description: "Generously thick winter luxury quilt for enduring warmth.",
      careInstructions: ["Specialist dry clean only"],
      dimensions: "King (108\" × 100\")",
      inStock: false,
      badge: "PREVIEW",
    },
  ],
};
